import type { Metadata } from "next";
import { fontSatoshi, fontAlpino } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Flexiana AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          // Paste your NEW, optimized Spline scene URL here
          href="https://prod.spline.design/lPFhmjX09AKt3iES/scene.splinecode"
          as="fetch"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${fontSatoshi.variable} ${fontAlpino.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
