import type { Metadata } from "next";
import { fontSatoshi, fontAlpino, fontHelvetica } from "./fonts";
import "./globals.css";
import SplinePrefetcher from "@/components/SplinePrefetcher";
import SmoothScrolling from "@/components/SmoothScrolling";

export const metadata: Metadata = {
  title: "Flexiana AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>
      <body
        className={`${fontSatoshi.variable} ${fontAlpino.variable} ${fontHelvetica.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <SmoothScrolling />
        {children}
        <SplinePrefetcher />
      </body>
    </html>
  );
}
